In [49]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv('table7.csv')
df

,Unnamed: 0,Police_Force_Name,Year,Quarter,Detailed_Offence_Description,Offence_Group,Offence_Subgroup,Number_of_Arrests,Arrests_Ranked,Level_of_Lockdown
0,0,Avon and Somerset,2020,1,Homicide,Violence against the person,Homicide,2,(-0.001. 20.0],High
1,1,Avon and Somerset,2020,1,Assault without injury on a constable,Violence against the person,Violence without injury,8,(-0.001. 20.0],High
2,2,Avon and Somerset,2020,1,Assault without injury,Violence against the person,Violence without injury,89,(80.0. 100.0],High
3,3,Avon and Somerset,2020,1,Racially or religiously aggravated assault wit...,Violence against the person,Violence without injury,1,(-0.001. 20.0],High
4,4,Avon and Somerset,2020,1,Modern slavery,Violence against the person,Violence without injury,2,(-0.001. 20.0],High
...,...,...,...,...,...,...,...,...,...,...
112781,112781,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,8,(-0.001. 20.0],Medium
112782,112782,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,15,(-0.001. 20.0],Medium
112783,112783,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,7,(-0.001. 20.0],Medium
112784,112784,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,11,(-0.001. 20.0],Medium
112785,112785,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,1,(-0.001. 20.0],Medium

In [51]:
df2 = df.sample(frac=0.1)
df2

,Unnamed: 0,Police_Force_Name,Year,Quarter,Detailed_Offence_Description,Offence_Group,Offence_Subgroup,Number_of_Arrests,Arrests_Ranked,Level_of_Lockdown
6780,6780,Devon and Cornwall,2020,1,Cruelty to children/young persons,Violence against the person,Violence without injury,6,(-0.001. 20.0],High
109856,109856,Thames Valley,2021,1,Other forgery,Miscellaneous crimes against society,Miscellaneous crimes,8,(-0.001. 20.0],Medium
70218,70218,Humberside,2021,3,Criminal damage to a dwelling,Criminal damage and arson,Criminal damage,156,(140.0. 160.0],Low
111182,111182,West Midlands,2021,1,Possession of other weapons,Possession of weapons offences,Possession of weapons offences,2,(-0.001. 20.0],Medium
106236,106236,South Wales,2021,1,Assault with injury,Violence against the person,Violence with injury,13,(-0.001. 20.0],Medium
...,...,...,...,...,...,...,...,...,...,...
78495,78495,South Yorkshire,2021,3,Exposure and voyeurism,Sexual offences,Other sexual offences,4,(-0.001. 20.0],Low
1773,1773,Surrey,2020,1,Malicious Communications,Violence against the person,Stalking and harassment,7,(-0.001. 20.0],High
98449,98449,Kent,2021,1,Making off without payment,Theft offences,Other theft offences,2,(-0.001. 20.0],Medium
95209,95209,Greater Manchester,2021,1,Burglary Residential,Theft offences,Domestic burglary,66,(60.0. 80.0],Medium
24790,24790,Thames Valley,2020,1,Theft in a dwelling other than from an automat...,Theft offences,Other theft offences,121,(120.0. 140.0],High

In [52]:
#df2.to_csv('tablesample.csv')

In [53]:
df3 = df.copy()
df3.Police_Force_Name.unique()

array(['Avon and Somerset', 'Bedfordshire', 'British Transport Police',
       'Cambridgeshire', 'Cheshire', 'Cleveland', 'Cumbria', 'Derbyshire',
       'Devon and Cornwall', 'Dorset', 'Durham', 'Dyfed-Powys', 'Essex',
       'Gloucestershire', 'Gwent', 'Hampshire', 'Hertfordshire',
       'Humberside', 'Kent', 'Lancashire', 'Leicestershire',
       'Lincolnshire', 'London. City of', 'Merseyside',
       'Metropolitan Police', 'Norfolk', 'North Wales', 'North Yorkshire',
       'Northamptonshire', 'Northumbria', 'Nottinghamshire',
       'South Wales', 'South Yorkshire', 'Staffordshire', 'Suffolk',
       'Surrey', 'Sussex', 'Thames Valley', 'Warwickshire', 'West Mercia',
       'West Midlands', 'West Yorkshire', 'Wiltshire',
       'Greater Manchester'], dtype=object)

In [54]:
df3.drop(labels=df3.columns[[0]],axis=1,inplace=True)
df3['Region'] = df3.Police_Force_Name.apply(lambda x: 'South East' if x in ['Essex','Kent','London. City of','Metropolitan Police','Hertfordshire',
                                                                           'Bedfordshire','Surrey','Hampshire','Thames Valley','Sussex'] else 'South West' if (x in ['Devon and Cornwall',
                                                                           'Dorset','Avon and Somerset','Wiltshire','Gloucestershire','Gwent','South Wales',
                                                                           'Dyfed-Powys','West Mercia','North Wales']) else 'West Midlands' if (x in ['Warwickshire','West Midlands',
                                                                            'Staffordshire','Derbyshire','Cheshire','Greater Manchester','Merseyside','Lancashire']) else 'East Midlands' 
                                                                            if (x in ['Suffolk','Cambridgeshire','Norfolk','Northamptonshire','Leicestershire','Lincolnshire','Nottinghamshire',
                                                                                    'South Yorkshire','Humberside','West Yorkshire']) else 'North' if (x in ['North Yorkshire','Durham',
                                                                                    'Northumbria','Cumbria','Cleveland']) else 'British Transport Police' if (x == 'British Transport Police') else 'butts')
df3

,Police_Force_Name,Year,Quarter,Detailed_Offence_Description,Offence_Group,Offence_Subgroup,Number_of_Arrests,Arrests_Ranked,Level_of_Lockdown,Region
0,Avon and Somerset,2020,1,Homicide,Violence against the person,Homicide,2,(-0.001. 20.0],High,South West
1,Avon and Somerset,2020,1,Assault without injury on a constable,Violence against the person,Violence without injury,8,(-0.001. 20.0],High,South West
2,Avon and Somerset,2020,1,Assault without injury,Violence against the person,Violence without injury,89,(80.0. 100.0],High,South West
3,Avon and Somerset,2020,1,Racially or religiously aggravated assault wit...,Violence against the person,Violence without injury,1,(-0.001. 20.0],High,South West
4,Avon and Somerset,2020,1,Modern slavery,Violence against the person,Violence without injury,2,(-0.001. 20.0],High,South West
...,...,...,...,...,...,...,...,...,...,...
112781,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,8,(-0.001. 20.0],Medium,South West
112782,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,15,(-0.001. 20.0],Medium,South West
112783,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,7,(-0.001. 20.0],Medium,South West
112784,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,11,(-0.001. 20.0],Medium,South West
112785,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,1,(-0.001. 20.0],Medium,South West

In [56]:
df3.Region.value_counts()

East Midlands               27420
South East                  26319
South West                  23826
West Midlands               21680
North                       12202
British Transport Police     1339
Name: Region, dtype: int64

In [57]:
df3.to_csv('tablewithregions')