In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('tablewithregions.csv')
df.drop(columns=['Unnamed: 0'],axis=1,inplace=True)

In [5]:
df

,Police_Force_Name,Year,Quarter,Detailed_Offence_Description,Offence_Group,Offence_Subgroup,Number_of_Arrests,Arrests_Ranked,Level_of_Lockdown,Region
0,Avon and Somerset,2020,1,Homicide,Violence against the person,Homicide,2,(-0.001. 20.0],High,South West
1,Avon and Somerset,2020,1,Assault without injury on a constable,Violence against the person,Violence without injury,8,(-0.001. 20.0],High,South West
2,Avon and Somerset,2020,1,Assault without injury,Violence against the person,Violence without injury,89,(80.0. 100.0],High,South West
3,Avon and Somerset,2020,1,Racially or religiously aggravated assault wit...,Violence against the person,Violence without injury,1,(-0.001. 20.0],High,South West
4,Avon and Somerset,2020,1,Modern slavery,Violence against the person,Violence without injury,2,(-0.001. 20.0],High,South West
...,...,...,...,...,...,...,...,...,...,...
112781,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,8,(-0.001. 20.0],Medium,South West
112782,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,15,(-0.001. 20.0],Medium,South West
112783,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,7,(-0.001. 20.0],Medium,South West
112784,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,11,(-0.001. 20.0],Medium,South West
112785,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,1,(-0.001. 20.0],Medium,South West

In [11]:
df['one'] = pd.cut(df.Number_of_Arrests,bins=np.arange(0,220,20),include_lowest=True)
df.one.value_counts()

(-0.001, 20.0]    88035
(20.0, 40.0]       8468
(40.0, 60.0]       3969
(60.0, 80.0]       2336
(80.0, 100.0]      1547
(100.0, 120.0]     1136
(120.0, 140.0]      841
(140.0, 160.0]      680
(160.0, 180.0]      528
(180.0, 200.0]      438
Name: one, dtype: int64

In [15]:
df['two'] = pd.cut(df.Number_of_Arrests,bins=np.arange(200,2100,100),include_lowest=False)
df.two.value_counts()

(200, 300]      1484
(300, 400]       869
(400, 500]       552
(500, 600]       388
(600, 700]       260
(700, 800]       196
(800, 900]       154
(900, 1000]      137
(1000, 1100]     115
(1100, 1200]      95
(1200, 1300]      85
(1300, 1400]      56
(1400, 1500]      46
(1600, 1700]      41
(1500, 1600]      40
(1700, 1800]      33
(1800, 1900]      33
(1900, 2000]      13
Name: two, dtype: int64

In [31]:
df['three'] = df.Number_of_Arrests.apply(lambda x: 'Over 2000' if x > 2000 else 'nan')
#df.three.value_counts()
df[df.three == 'Over 2000']

,Police_Force_Name,Year,Quarter,Detailed_Offence_Description,Offence_Group,Offence_Subgroup,Number_of_Arrests,Arrests_Ranked,Level_of_Lockdown,Region,one,two,three,test
2264,Avon and Somerset,2020,1,Assault without injury,Violence against the person,Violence without injury,2054,Over 2000,High,South West,nan,nan,Over 2000,nannanOver 2000
3639,British Transport Police,2020,1,Theft from the person,Theft offences,Theft from the person,2971,Over 2000,High,British Transport Police,nan,nan,Over 2000,nannanOver 2000
3688,British Transport Police,2020,1,Other theft,Theft offences,Other theft offences,2223,Over 2000,High,British Transport Police,nan,nan,Over 2000,nannanOver 2000
4504,Cheshire,2020,1,Assault without injury,Violence against the person,Violence without injury,2004,Over 2000,High,West Midlands,nan,nan,Over 2000,nannanOver 2000
9040,Essex,2020,1,Assault without injury,Violence against the person,Violence without injury,2908,Over 2000,High,South East,nan,nan,Over 2000,nannanOver 2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111584,West Midlands,2021,1,Malicious Communications,Violence against the person,Stalking and harassment,2156,Over 2000,Medium,West Midlands,nan,nan,Over 2000,nannanOver 2000
111640,West Midlands,2021,1,Public fear. alarm or distress,Public order offences,Public order offences,3005,Over 2000,Medium,West Midlands,nan,nan,Over 2000,nannanOver 2000
111671,West Yorkshire,2021,1,Assault without injury,Violence against the person,Violence without injury,3094,Over 2000,Medium,East Midlands,nan,nan,Over 2000,nannanOver 2000
112276,West Yorkshire,2021,1,Malicious Communications,Violence against the person,Stalking and harassment,2139,Over 2000,Medium,East Midlands,nan,nan,Over 2000,nannanOver 2000
112362,West Yorkshire,2021,1,Public fear. alarm or distress,Public order offences,Public order offences,2067,Over 2000,Medium,East Midlands,nan,nan,Over 2000,nannanOver 2000

In [32]:
df.one, df.two, df.three = df.one.astype('str'),df.two.astype('str'),df.three.astype('str')

In [33]:
df['test'] = df.one + df.two + df.three
df

,Police_Force_Name,Year,Quarter,Detailed_Offence_Description,Offence_Group,Offence_Subgroup,Number_of_Arrests,Arrests_Ranked,Level_of_Lockdown,Region,one,two,three,test
0,Avon and Somerset,2020,1,Homicide,Violence against the person,Homicide,2,(-0.001. 20.0],High,South West,"(-0.001, 20.0]",nan,nan,"(-0.001, 20.0]nannan"
1,Avon and Somerset,2020,1,Assault without injury on a constable,Violence against the person,Violence without injury,8,(-0.001. 20.0],High,South West,"(-0.001, 20.0]",nan,nan,"(-0.001, 20.0]nannan"
2,Avon and Somerset,2020,1,Assault without injury,Violence against the person,Violence without injury,89,(80.0. 100.0],High,South West,"(80.0, 100.0]",nan,nan,"(80.0, 100.0]nannan"
3,Avon and Somerset,2020,1,Racially or religiously aggravated assault wit...,Violence against the person,Violence without injury,1,(-0.001. 20.0],High,South West,"(-0.001, 20.0]",nan,nan,"(-0.001, 20.0]nannan"
4,Avon and Somerset,2020,1,Modern slavery,Violence against the person,Violence without injury,2,(-0.001. 20.0],High,South West,"(-0.001, 20.0]",nan,nan,"(-0.001, 20.0]nannan"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112781,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,8,(-0.001. 20.0],Medium,South West,"(-0.001, 20.0]",nan,nan,"(-0.001, 20.0]nannan"
112782,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,15,(-0.001. 20.0],Medium,South West,"(-0.001, 20.0]",nan,nan,"(-0.001, 20.0]nannan"
112783,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,7,(-0.001. 20.0],Medium,South West,"(-0.001, 20.0]",nan,nan,"(-0.001, 20.0]nannan"
112784,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,11,(-0.001. 20.0],Medium,South West,"(-0.001, 20.0]",nan,nan,"(-0.001, 20.0]nannan"
112785,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,1,(-0.001. 20.0],Medium,South West,"(-0.001, 20.0]",nan,nan,"(-0.001, 20.0]nannan"

In [36]:
df.test = df.test.astype('str').str.replace(',','.',regex=True)
df.test = df.test.str.replace('nan','',regex=True)

In [41]:
df.test.value_counts()

(-0.001. 20.0]    88035
(20.0. 40.0]       8468
(40.0. 60.0]       3969
(60.0. 80.0]       2336
(80.0. 100.0]      1547
(200. 300]         1484
(100.0. 120.0]     1136
(300. 400]          869
(120.0. 140.0]      841
(140.0. 160.0]      680
(400. 500]          552
(160.0. 180.0]      528
(180.0. 200.0]      438
(500. 600]          388
(600. 700]          260
Over 2000           211
(700. 800]          196
(800. 900]          154
(900. 1000]         137
(1000. 1100]        115
(1100. 1200]         95
(1200. 1300]         85
(1300. 1400]         56
(1400. 1500]         46
(1600. 1700]         41
(1500. 1600]         40
(1800. 1900]         33
(1700. 1800]         33
(1900. 2000]         13
Name: test, dtype: int64

In [44]:
#df.drop(columns=['one','two','three','Arrests_Ranked'],axis=1,inplace=True)
df.rename(columns={'test':'Arrests_Ranked'},inplace=True)
df

,Police_Force_Name,Year,Quarter,Detailed_Offence_Description,Offence_Group,Offence_Subgroup,Number_of_Arrests,Level_of_Lockdown,Region,Arrests_Ranked
0,Avon and Somerset,2020,1,Homicide,Violence against the person,Homicide,2,High,South West,(-0.001. 20.0]
1,Avon and Somerset,2020,1,Assault without injury on a constable,Violence against the person,Violence without injury,8,High,South West,(-0.001. 20.0]
2,Avon and Somerset,2020,1,Assault without injury,Violence against the person,Violence without injury,89,High,South West,(80.0. 100.0]
3,Avon and Somerset,2020,1,Racially or religiously aggravated assault wit...,Violence against the person,Violence without injury,1,High,South West,(-0.001. 20.0]
4,Avon and Somerset,2020,1,Modern slavery,Violence against the person,Violence without injury,2,High,South West,(-0.001. 20.0]
...,...,...,...,...,...,...,...,...,...,...
112781,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,8,Medium,South West,(-0.001. 20.0]
112782,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,15,Medium,South West,(-0.001. 20.0]
112783,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,7,Medium,South West,(-0.001. 20.0]
112784,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,11,Medium,South West,(-0.001. 20.0]
112785,Wiltshire,2021,1,Racially or religiously aggravated public fear...,Public order offences,Public order offences,1,Medium,South West,(-0.001. 20.0]

In [45]:
df.Arrests_Ranked.value_counts()

(-0.001. 20.0]    88035
(20.0. 40.0]       8468
(40.0. 60.0]       3969
(60.0. 80.0]       2336
(80.0. 100.0]      1547
(200. 300]         1484
(100.0. 120.0]     1136
(300. 400]          869
(120.0. 140.0]      841
(140.0. 160.0]      680
(400. 500]          552
(160.0. 180.0]      528
(180.0. 200.0]      438
(500. 600]          388
(600. 700]          260
Over 2000           211
(700. 800]          196
(800. 900]          154
(900. 1000]         137
(1000. 1100]        115
(1100. 1200]         95
(1200. 1300]         85
(1300. 1400]         56
(1400. 1500]         46
(1600. 1700]         41
(1500. 1600]         40
(1800. 1900]         33
(1700. 1800]         33
(1900. 2000]         13
Name: Arrests_Ranked, dtype: int64